version: "3.8"

services:
  db:
    image: postgres:17
    env_file:
      - ./InnovationLabBackend.Api/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: InnovationLabBackend.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./InnovationLabBackend.Api/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    working_dir: /app
    command: ["dotnet", "InnovationLabBackend.Api.dll"]
volumes:
  pgdata:
